project:
  type: website

website:
  title: "earthquakes"
#  navbar:
#    left:
#      - href: index.qmd
#        text: Home
#      - about.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true



